Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/05/2017
Var
cont, soma, numero, min, max: inteiro

Inicio
cont=0
min-100
max-0
soma=0
repita
  escreva("Digite o número: ")
  leia (numero)
  soma:=
       se (Soma=100) ou (numero=0) ou (cont=13) entao
cont:= cont+1
              


Fimalgoritmo