Algoritmo "exercicio12"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Alexandre gatelli
// Descrição   : aula7
// Autor(a)    : Alam do nascimento padilha
// Data atual  : 11/04/2017
Var
in,po: real

Inicio
escreval ("Digite o número inteiro: ")
leia (in)
se in <=0 entao
po:= in*-1
escreval("O número negativo transformado é: ", po)
fimse
se in >=0 entao
po:= in*1
escreval("O número positivo transformado é: ", po)
fimse

Fimalgoritmo
