Algoritmo "exercicio3"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Alexandre gatelli
// Descrição   : aula7
// Autor(a)    : Alam do nascimento padilha
// Data atual  : 11/04/2017
Var
A,B: real

Inicio
escreva("Digite o valo de A: ")
leia(A)
escreva("Digite o valor de B: ")
leia(B)
se (A>B) entao
A:= A-B
escreva("O maior é A e a diferença é:", A)
senao
B:= B-A
escreva("O maior é B e a diferença é:", B)
fimse



Fimalgoritmo
