algoritmo "estoque"

Var
peso, altura, imc: real
Inicio
  escreval("Entre com seu peso(kg): " )
  leia(peso)
      escreval("Entre com sua altura: ")
      leia(altura)
      escreval("")
      imc <-(peso/((altura/100)*2)))
      
          se (imc <= 18.5) entao
          
      escreval("Você está abaixo do peso ideal: ", imc)
      senao
      
          se(imc <= 24.9)entao
          
      escreval("Parabéns, Você está no seu peso ideal :", imc)
      fimse
      

      

Fimalgoritmo